### ISSUE TITLE
Add full support for Apple Silicon

### ISSUE THREAD

**Issue by ihor-sviziev** [swiftotter/den#7] opened 2022-06-24 15:21 UTC
Currently, warden support for ARM isn't full yet. Would be great to have ARM-optmized all the images.
More details about current status: https://github.com/davidalger/warden/issues/341#issuecomment-1087368727

Images:
- [x] MySQL
- [x] MariaDB
- [x] ElasticSearch
- [x] OpenSearch
- [x] Redis
- [x] PHP-FPM
- [x] Nginx
- [x] Varnish
- [x] RabbitMQ
- [x] MagePack
- [x] Selenium
- [x] Allure
- [x] Magepack
- [x] Core: Traefik
- [x] Core: Mailhog
- [x] Core: DnsMasq
- [x] Core: Tunnel
- [x] Core: Portainer

**Comment by navarr** [comment] 2022-06-24 15:22
I'm going to close this as a duplicate of #3 because the purpose of #3 is to have ARM-optimized images 😄 
I'll quickly update #3 to be clearer on this.

**Comment by navarr** [comment] 2022-06-24 15:24
I changed my mind, as we should double-check _all_ images to ensure they're ARM-optimized

**Comment by ihor-sviziev** [comment] 2022-06-24 15:24
right :)

**Closed** 2022-08-23 20:56 UTC
